language: cpp

git:
  submodules: true
  quiet: false
  depth: false

compiler: gcc
dist: xenial
cache: ccache

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-5

before_script:
  - bash scripts/install_dependencies.sh

script:
  - pwd
  - echo -e "\033[42;31m variable LD_LIBRARY_PATH is ${LD_LIBRARY_PATH} \033[0m"
  - sudo ldconfig
  - cd src/apollo
  - mkdir -p build
  - cd build && cmake ..
  - make -j$(nproc)
  - sudo make install
  - cd ../../../
  - bash run_all_test.bash

notifications:
  email: false
